#!/usr/bin/python2

from bcc import BPF
import time

prog="""
#include <uapi/linux/ptrace.h>
#include <bcc/proto.h>

#include <linux/sched.h>

RAW_TRACEPOINT_PROBE(pelt_se)
{
    struct sched_entity *se = (struct sched_entity *)ctx->args[0];

    bpf_trace_printk("pelt_se: util_avg=%d load_avg=%d\\n", se->avg.util_avg, se->avg.load_avg);

    return 0;
}
"""

if not BPF.support_raw_tracepoint():
    print "Booo Raw Trace Points are not supported..."
    exit()

b = BPF(text=prog)
#time.sleep(10)
b.trace_print()
